server:
    port: 8090
    address: localhost

spring:
    datasource:
        url: jdbc:mysql://192.168.0.107:3306/binjiang?allowMultiQueries=true
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
    http:
        encoding.charset: UTF-8
#        encoding.enable: true
        encoding.force: true

mybatis:
    configLocation: classpath:config/mybatis-config.xml
#   配置typeAliasesPackage后parameterType不用写全称
    typeAliasesPackage: com.vae.wechat.modal
#   配置typeHandlersPackage把java类型当做数据库类型
#    typeHandlersPackage: com.vae.wechat.dao
    mapperLocations: classpath:mapper/*.xml

logging:
    level:
       com.ibatis:DEBUG